import type { TextStyle, ViewStyle } from "react-native";

export const DS = {
  colors: {
    bg: "#F7F4EF",
    surface: "#FFFFFF",
    surfaceAlt: "#EDE8DF",
    border: "#C8C0B4",
    borderSoft: "#D8D0C4",
    text: "#1C2318",
    textMuted: "#4A5544",
    textFaint: "#8A9585",
    primary: "#2A5C3F",
    primarySoft: "#EBF2ED",
    primaryMid: "#5C8B6E",
    danger: "#C4623A",
    dangerSoft: "#F0E0D8",
    amber: "#B87A2A",
    amberSoft: "#F2E8D5",
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 24,
    xxl: 36,
    xxxl: 56,
    screenX: 16,
    screenSectionGap: 16,
  },
  radius: {
    sm: 6,
    md: 12,
    lg: 20,
    pill: 999,
  },
  shadow: {
    card: {
      shadowColor: "#1C2318",
      shadowOpacity: 0.08,
      shadowRadius: 12,
      shadowOffset: { width: 0, height: 6 },
      elevation: 4,
    } satisfies ViewStyle,
    cardSoft: {
      shadowColor: "#1C2318",
      shadowOpacity: 0.05,
      shadowRadius: 8,
      shadowOffset: { width: 0, height: 3 },
      elevation: 2,
    } satisfies ViewStyle,
  },
  typography: {
    display: {
      fontFamily: "System",
      fontWeight: "400",
      fontSize: 34,
      lineHeight: 40,
      color: "#1C2318",
      letterSpacing: -0.5,
    } satisfies TextStyle,
    title: {
      fontFamily: "System",
      fontWeight: "400",
      fontSize: 20,
      lineHeight: 24,
      color: "#1C2318",
      letterSpacing: 0.2,
    } satisfies TextStyle,
    body: {
      fontFamily: "System",
      fontWeight: "400",
      fontSize: 14,
      lineHeight: 20,
      color: "#1C2318",
    } satisfies TextStyle,
    bodyStrong: {
      fontFamily: "System",
      fontWeight: "700",
      fontSize: 14,
      lineHeight: 20,
      color: "#1C2318",
    } satisfies TextStyle,
    caption: {
      fontFamily: "System",
      fontWeight: "400",
      fontSize: 12,
      lineHeight: 16,
      color: "#8A9585",
    } satisfies TextStyle,
    mono: {
      fontFamily: "System",
      fontWeight: "400",
      fontSize: 10,
      lineHeight: 14,
      letterSpacing: 0.8,
      textTransform: "uppercase",
      color: "#8A9585",
    } satisfies TextStyle,
  },
} as const;
